version: '3.8'

services:
  stock-api:
    build: .
    ports:
      - "8000:8000"
    restart: always

  stock-prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
      - "9090:9090"
    depends_on:
      - stock-api
    restart: always

  stock-grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - "3000:3000"
    depends_on:
      - stock-prometheus
    restart: always
